experiment_name: gsm8k-grpo
trial_name: trial0

seed: 1
enable_offload: false
total_train_epochs: 10
tokenizer_path: ${actor.path}

cluster:
  n_nodes: 1
  n_gpus_per_node: 8
  fileroot: /tmp/areal/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /tmp/areal/name_resolve

scheduler:
  type: null

rollout:
  backend: "vllm:d1p1t1"
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  max_concurrent_rollouts: 256
  queue_size: null
  consumer_batch_size: ${train_dataset.batch_size}
  max_head_offpolicyness: 2
  enable_rollout_tracing: false
  scheduling_spec: ${actor.scheduling_spec}
  fileroot: ${cluster.fileroot}
  tokenizer_path: ${tokenizer_path}
  dump_to_file: true

gconfig:
  n_samples: 4
  min_new_tokens: 0
  max_new_tokens: 2048
  greedy: false
  temperature: 1.0

actor:
  backend: "fsdp:d1p1t1"
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: /home/zahra/models/Qwen3-0.6B
  init_from_scratch: false
  disable_dropout: true
  gradient_checkpointing: true
  dtype: bfloat16
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer:
    type: adam
    lr: 1e-6
    weight_decay: 0.017
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    lr_scheduler_type: constant
    gradient_clipping: 1.0
    warmup_steps_proportion: 0.001
  eps_clip: 0.4
  temperature: ${gconfig.temperature}
  reward_scaling: 10.0
  reward_bias: -0.5
  kl_ctl: 0.0
  ppo_n_minibatches: 1
  recompute_logprob: true
  use_decoupled_loss: true
  rejection_sampling:
    metric: ratio
    upper: 5.0
  reward_norm:
    mean_level: group
    std_level: group
    group_size: ${gconfig.n_samples}
  adv_norm:
    mean_level: batch
    std_level: batch
  weight_update_mode: xccl
  max_new_tokens: ${gconfig.max_new_tokens}
  scheduling_spec:
    - task_type: worker
      port_count: 2
      gpu: 1
      mem: 32
      cmd: python3 -m areal.infra.rpc.rpc_server
      env_vars: {}

teacher:
  teachers:
    - engine_type: rollout
      path: /home/zahra/models/Qwen3-8B
      weight: 1.0
      rollout:
        backend: "vllm:d1p1t1"
        scheduling_spec:
          - task_type: worker
            port_count: 2
            gpu: 1
            mem: 32
            cmd: python3 -m areal.infra.rpc.rpc_server
            env_vars: {}
    - engine_type: rollout
      path: /home/zahra/models/Qwen2.5-14B-Instruct
      weight: 1.0
      rollout:
        backend: "vllm:d1p1t2"
        scheduling_spec:
          - task_type: worker
            port_count: 2
            gpu: 1
            mem: 32
            cmd: python3 -m areal.infra.rpc.rpc_server
            env_vars: {}
  teacher_weighting: adaptive

  competence_warmup_steps: 30

  competence_tau_c_max: 0.1
  competence_tau_c_min: 0.05

  competence_tau_s_min: 0.0
  competence_tau_s_max: 1

  rl_loss_weight: 1.0
  distill_loss_weight: 5e-2

ref:
  backend: ${actor.backend}
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  path: ${actor.path}
  init_from_scratch: false
  disable_dropout: true
  dtype: ${actor.dtype}
  mb_spec:
    max_tokens_per_mb: 10240
  optimizer: null
  scheduling_strategy:
    type: colocation
    target: actor
  scheduling_spec: ${actor.scheduling_spec}

# SGLang
sglang:
  model_path: ${actor.path}
  random_seed: ${seed}
  skip_tokenizer_init: true
  dtype: ${actor.dtype}
  max_running_requests: null
  context_length: 32768
  mem_fraction_static: 0.8

vllm:
  model: ${actor.path}
  seed: ${seed}
  skip_tokenizer_init: false
  dtype: ${actor.dtype}
  max_model_len: 32768
  gpu_memory_utilization: 0.8
  enforce_eager: True

# datasets
train_dataset:
  batch_size: 256
  shuffle: true
  pin_memory: true
  num_workers: 4
  path: /home/zahra/datasets/gsm8k
  type: rl
  max_length: 1024

valid_dataset:
  batch_size: 256
  pin_memory: true
  num_workers: 4
  path: /home/zahra/datasets/gsm8k
  type: rl

# Utilities
saver:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: null
  freq_steps: null
  freq_secs: null

recover:
  mode: disabled
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: null
  freq_steps: null
  freq_secs: 3600

evaluator:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  freq_epochs: 1
  freq_steps: null
  freq_secs: null

stats_logger:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  wandb:
    mode: disabled
  swanlab:
    project: ada_mopd
    name: gsm8k_multi_teacher_5e-2
    mode: cloud
    api_key: CHqueBePouUJGo8kgtGXR

perf_tracer:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  enabled: false
  session_tracer:
    enabled: false
